#!/usr/bin/env bash
# Build a production release tarball + SHA-256 manifest for judge distribution.
# Run locally after training; does not upload anywhere.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PYTHON="${PYTHON:-python3}"
if [[ -x "$ROOT/.venv/bin/python" ]]; then
  PYTHON="$ROOT/.venv/bin/python"
fi

OUT_DIR="$ROOT/benchmark"
MANIFEST="$OUT_DIR/ARTIFACT_MANIFEST.json"
TARBALL="$OUT_DIR/svamitva_production_benchmark.tar.gz"

mkdir -p "$OUT_DIR"

for f in outputs/checkpoints/best_model.pth outputs/checkpoints/latest_model.pth outputs/optimal_bias.json; do
  [[ -f "$ROOT/$f" ]] || { echo "Missing $f — train or fetch artifacts first." >&2; exit 1; }
done

echo "==> Creating release tarball"
tar -czf "$TARBALL" \
  outputs/checkpoints/best_model.pth \
  outputs/checkpoints/latest_model.pth \
  outputs/optimal_bias.json \
  $(find data -type f \( -name '*.tif' -o -name '*.shp' -o -name '*.shx' -o -name '*.dbf' -o -name '*.prj' \) 2>/dev/null || true)

echo "==> Writing manifest with SHA-256 checksums"
"$PYTHON" - <<PY
import hashlib, json
from pathlib import Path

root = Path("$ROOT")
paths = [
    "outputs/checkpoints/best_model.pth",
    "outputs/checkpoints/latest_model.pth",
    "outputs/optimal_bias.json",
]

def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        while chunk := f.read(1024 * 1024):
            h.update(chunk)
    return h.hexdigest()

manifest = {
    "release_version": "1.0.0",
    "description": "Production benchmark bundle generated by scripts/package_production_release.sh",
    "license_note": "Redistribute only if authorized under hackathon/SVAMITVA data terms.",
    "tarball": "benchmark/svamitva_production_benchmark.tar.gz",
    "artifacts": [
        {"path": p, "sha256": sha256(root / p), "role": p}
        for p in paths
    ],
}
out = root / "benchmark" / "ARTIFACT_MANIFEST.json"
out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
print(f"Wrote {out}")
for a in manifest["artifacts"]:
    print(f"  {a['path']}: {a['sha256'][:16]}…")
PY

echo "==> Done"
echo "  Tarball: $TARBALL"
echo "  Manifest: $MANIFEST"
echo "  Host tarball and set SVAMITVA_ARTIFACTS_URL for judges."
